# Generated by Django 5.2.3 on 2025-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal_chat", "0002_rename_text_message_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_uploads/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
